In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
Training_Dir = '/content/drive/My Drive/final_train_2'
Testing_Dir = '/content/drive/My Drive/test'

In [ ]:
import tensorflow as tf
import keras_preprocessing
from keras_preprocessing import image
from keras_preprocessing.image import ImageDataGenerator
import keras

Using TensorFlow backend.


In [ ]:
training_datagen = ImageDataGenerator(rescale = 1./255)

testing_datagen = ImageDataGenerator(rescale = 1./255)

train_generator = training_datagen.flow_from_directory(
	Training_Dir,
	target_size=(224,224),
  shuffle=True,
	class_mode='categorical'
)


testing_generator = testing_datagen.flow_from_directory(
	Testing_Dir,
	target_size=(224,224),
  shuffle=True,
	class_mode='categorical'
)

Found 38261 images belonging to 26 classes.
Found 104 images belonging to 26 classes.


In [ ]:
import numpy as np
np.unique(train_generator.classes)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25], dtype=int32)

In [ ]:
train_generator.class_indices,testing_generator.class_indices

({'A': 0,
  'B': 1,
  'C': 2,
  'D': 3,
  'E': 4,
  'F': 5,
  'G': 6,
  'H': 7,
  'I': 8,
  'J': 9,
  'K': 10,
  'L': 11,
  'M': 12,
  'N': 13,
  'O': 14,
  'P': 15,
  'Q': 16,
  'R': 17,
  'S': 18,
  'T': 19,
  'U': 20,
  'V': 21,
  'W': 22,
  'X': 23,
  'Y': 24,
  'Z': 25},
 {'A': 0,
  'B': 1,
  'C': 2,
  'D': 3,
  'E': 4,
  'F': 5,
  'G': 6,
  'H': 7,
  'I': 8,
  'J': 9,
  'K': 10,
  'L': 11,
  'M': 12,
  'N': 13,
  'O': 14,
  'Q': 15,
  'R': 16,
  'S': 17,
  'T': 18,
  'U': 19,
  'V': 20,
  'W': 21,
  'X': 22,
  'Y': 23,
  'Z': 24,
  'p': 25})

In [ ]:
np.unique(train_generator.classes, return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25], dtype=int32),
 array([1500, 1500, 1500, 1500, 1500, 1500, 1500, 1500, 1510, 1500, 1500,
        1540, 1500, 1500, 1500, 1500, 1500, 1500, 1500, 1500,  711, 1500,
        1500, 1500, 1500, 1500]))

In [ ]:
np.unique(testing_generator.classes, return_counts = True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25], dtype=int32),
 array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4]))

In [ ]:
model = tf.keras.models.Sequential([
    # Note the input shape is the desired size of the image 150x150 with 3 bytes color
    # This is the first convolution
    tf.keras.layers.Conv2D(16, (3,3), activation='relu', input_shape=(224,224,3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Dropout(.25),
    # The second convolution
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Dropout(.25),
        # The second convolution
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Dropout(.25),
        # The second convolution
    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Dropout(.25),

    # Flatten the results to feed into a DNN
    tf.keras.layers.Flatten(),
    # 512 neuron hidden layer
    tf.keras.layers.Dense(512, activation='relu'),

    tf.keras.layers.Dense(26, activation='softmax')
])

In [ ]:
#only to load pretrained model....

from keras.models import load_model
from keras.preprocessing import image

model = tf.keras.models.load_model('/content/drive/My Drive/FinalPretrainModel.hdf5')
model.layers[0].input_shape

(None, 224, 224, 3)

In [ ]:
#only to load pretrained model....

from keras.models import load_model
from keras.preprocessing import image

model = tf.keras.models.load_model('/content/drive/My Drive/FinalPretrainModel.hdf5')
model.layers[0].input_shape
model.layers[1].input_shape
model.layers[2].input_shape
model.layers[3].input_shape

ValueError: ignored

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
mobilenetv2_1.00_224 (Model) (None, 7, 7, 1280)        2257984   
_________________________________________________________________
conv2d (Conv2D)              (None, 5, 5, 32)          368672    
_________________________________________________________________
dropout (Dropout)            (None, 5, 5, 32)          0         
_________________________________________________________________
global_average_pooling2d (Gl (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 26)                858       
Total params: 2,627,514
Trainable params: 2,593,402
Non-trainable params: 34,112
_________________________________________________________________


In [ ]:
model.compile(loss = 'categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [ ]:
from keras.callbacks import ModelCheckpoint
filepath = "/content/drive/My Drive/FinalPretrainModel.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]
history = model.fit_generator(train_generator, epochs=3, verbose = 1, callbacks= callbacks_list)


Epoch 1/3
1195/1196 [============================>.] - ETA: 8s - loss: 0.2930 - acc: 0.9241 
Epoch 00001: acc improved from -inf to 0.92420, saving model to /content/drive/My Drive/FinalPretrainModel.hdf5
1196/1196 [==============================] - 10452s 9s/step - loss: 0.2928 - acc: 0.9242
Epoch 2/3
1195/1196 [============================>.] - ETA: 0s - loss: 0.1774 - acc: 0.9566
Epoch 00002: acc improved from 0.92420 to 0.95661, saving model to /content/drive/My Drive/FinalPretrainModel.hdf5
1196/1196 [==============================] - 225s 188ms/step - loss: 0.1772 - acc: 0.9566
Epoch 3/3
1195/1196 [============================>.] - ETA: 0s - loss: 0.1399 - acc: 0.9662
Epoch 00003: acc improved from 0.95661 to 0.96615, saving model to /content/drive/My Drive/FinalPretrainModel.hdf5
1196/1196 [==============================] - 224s 187ms/step - loss: 0.1398 - acc: 0.9662


In [ ]:
from keras.callbacks import ModelCheckpoint
filepath = "/content/drive/My Drive/FinalPretrainModel.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]
history = model.fit_generator(train_generator, epochs=2, verbose = 1, callbacks= callbacks_list)


In [ ]:
#-----------------------------------------------------------train---------------------------------------------------------------
import numpy as np
y_train_pred = model.predict_generator(train_generator)
y_train = train_generator.classes[train_generator.index_array]
y_train_pred = np.argmax(y_train_pred, axis=-1)

In [ ]:
from sklearn.metrics import confusion_matrix
import itertools
cnf_matrix = confusion_matrix(y_train, y_train_pred)

In [ ]:
cnf_matrix

array([[1268,    0,    0,    0,   15,    0,    0,   13,   14,    0,    0,
           4,    0,    0,    4,    0,    0,    0,   80,   76,    0,    0,
           0,   16,   10,    0],
       [   5, 1332,    2,    0,  105,    9,    7,   21,    2,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    8,    0,    0,
           0,    8,    1,    0],
       [   0,   35, 1015,    6,    5,   22,  101,   44,   12,    0,    0,
          94,    0,    0,   84,    0,    0,    2,   25,   18,    0,    0,
           0,   26,   11,    0],
       [   1,    0,    3, 1335,    1,    5,    7,    4,   30,    0,    0,
          64,    0,    0,    8,    0,    0,    8,    0,    0,    0,    0,
           0,   34,    0,    0],
       [   0,    0,    0,   32, 1237,    6,   19,   27,   24,    0,    0,
           1,    0,    0,   18,    0,    0,    0,   97,   33,    0,    0,
           0,    6,    0,    0],
       [   0,    0,    0,    6,    0, 1484,    1,    0,    1,    0,    0,
           2,    0,  

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_train_pred)

0.6542693604453621

In [ ]:
from sklearn.metrics import classification_report
target_names = ['A', 'B', 'C', 'D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

In [ ]:
print(classification_report(y_train, y_train_pred, target_names=target_names))

              precision    recall  f1-score   support

           A       0.69      0.85      0.76      1500
           B       0.95      0.89      0.92      1500
           C       0.76      0.68      0.72      1500
           D       0.76      0.89      0.82      1500
           E       0.76      0.82      0.79      1500
           F       0.67      0.99      0.80      1500
           G       0.65      0.90      0.75      1500
           H       0.36      0.99      0.53      1500
           I       0.63      0.91      0.75      1510
           J       1.00      0.30      0.46      1500
           K       0.75      0.44      0.56      1500
           L       0.69      0.99      0.82      1540
           M       0.98      0.65      0.78      1500
           N       0.44      0.04      0.08      1500
           O       0.56      0.67      0.61      1500
           P       0.77      0.56      0.65      1500
           Q       0.60      0.20      0.30      1500
           R       0.93    

In [ ]:
#---------------------------------------------------------------test--------------------------------------------------------
y_test_pred = model.predict_generator(testing_generator)
y_test = testing_generator.classes[testing_generator.index_array]
y_test_pred = np.argmax(y_test_pred, axis=-1)

In [ ]:
from sklearn.metrics import confusion_matrix
import itertools
cnf_matrix_test = confusion_matrix(y_test, y_test_pred)

In [ ]:
cnf_matrix_test

array([[0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_pred)

0.04807692307692308